#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mediamtx"
name = "MediaMTX"
description.en = "Media router that routes media streams from one end to the other"
description.fr = "Routeur média qui transfère les flux d'un point à un autre"

version = "1.18.1~ynh1"

maintainers = [ "OniriCorpe" ]

[upstream]
license = "MIT"
website = "https://mediamtx.org/"
admindoc = "https://mediamtx.org/docs/references/configuration-file"
code = "https://github.com/bluenviron/mediamtx"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"

# FIXME: replace with an **estimate** minimum disk and RAM requirements. e.g. 20M, 400M, 1G...
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]
    [resources.sources.main]
    amd64.url = "https://github.com/bluenviron/mediamtx/releases/download/v1.18.1/mediamtx_v1.18.1_linux_amd64.tar.gz"
    amd64.sha256 = "b02cc1940885d4f383329a832b97372558e987205c8fd8276f6626ae84428c04"
    arm64.url = "https://github.com/bluenviron/mediamtx/releases/download/v1.18.1/mediamtx_v1.18.1_linux_arm64.tar.gz"
    arm64.sha256 = "35fe022ac3aab2c26a97472d715798617b56bdfef6ed3e063e52603896971cf1"
    armhf.url = "https://github.com/bluenviron/mediamtx/releases/download/v1.18.1/mediamtx_v1.18.1_linux_armv7.tar.gz"
    armhf.sha256 = "64eb41865982a2e9b62bb66f6e40f8be3ba0e4d74a66f9fdceb3d4fee91e954a"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
